### ISSUE TITLE
Parameter referenced from components are not detected

### ISSUE THREAD

**Issue by terribleherbst** [codecentric/hikaku#23]
**Setup information**
hikaku version: 1.1.0
specification converter: OpenApiConverter
implementation converter: SpringConverter
build tool and version gradle
test framework spock

**Describe the bug**
In my OpenAPI specification I have described parameter like the following in the path sectio
```yaml
parameters:
        - $ref: "#/components/parameters/tenantParam"
        - name: qrCode
          in: query
          example: 0101234567890123sd0DE012-1234567-xyz
          description: The qr code 
          schema:
            type: string
```
In the parameter section tenantParam is described as
```yaml
    tenantParam:
      name: tenant
      in: query
      description: The tenant of a user
      schema:
        $ref: "#/components/schemas/Tenant"
      example: de
```

And the schema as
```yaml
    Tenant:
      type: string
      minLength: 2
      maxLength: 2
      example: de
```

While the qrCode parameter is checked as expected the tenant parameter is shown as _Unexpected but found_ and not listed in the report.

**Expected behavior**
Parmeters should be handled the same when added directly in the param section as when a reference is used. The same seems to happen with all other referenced parameters.

**Code samples**:
Can you provide specifications or code snippets?
```groovy
  def "Check implementation vs specification of api"() {
    given:
      def path = Paths.get("../spec/my-api.yaml")
      OpenApiConverter openApiConverter = OpenApiConverter.usingPath(path);
      SpringConverter springConverter = new SpringConverter(springContext);

      HikakuConfig hikakuConfig = new HikakuConfig(
        [SpringConverter.IGNORE_ERROR_ENDPOINT] as Set,
        true,
        true
      );

    when:
      def hikaku = new Hikaku(
        openApiConverter,
        springConverter,
        hikakuConfig
      )
    then:
      hikaku.match();
  }
```

**Comment by cc-jhr** [comment]
Hello @terribleherbst ,
thank you very much for reporting this issue. You are absolutely right. For the media types, both the inline declaration and the referenced components are taken into account. I missed out on it for the parameters.

**Comment by cc-jhr** [comment]
I just fixed this issue. You could check the 2.0.0-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/
In 2.0.0 following changed took please, which you should adjust your code to:
* Renamed package de.codecentric.hikaku.converter to de.codecentric.hikaku.converters
* Renamed package de.codecentric.hikaku.reporter to de.codecentric.hikaku.reporters
* Removed static methods usingPath() and usingFile in Java usage.

**Comment by terribleherbst** [comment]
That was really fast! Thanks a lot, the SNAPSHOT version works as expected.

**Comment by cc-jhr** [comment]
Perfect! I plan to release the 2.0.0 this week.
