### ISSUE TITLE
Support equals if content type matches and ignore charset

### ISSUE THREAD

**Issue by terribleherbst** [codecentric/hikaku#25]
**Setup information**
hikaku version: 2.0.0-SNAPSHOT
specification converter: OpenApiConverter
implementation converter: SpringConverter

**Describe the bug**
When the API specification states `application/json` as content type byt the implementation return `application/json;charset=UTF-8` they are not treated as equals. I am not sure if this is bug or maybe more a feature request (and there seems only be a bug template here), but if the implementation fullfills a contract the match should be OK. 

**Expected behavior**
IMHO `application/json;charset=UTF-8` is a valid implementation when `application/json` is required and should not be reported as an error.

**Comment by cc-jhr** [comment]
Interesting topic.
First question that comes to my mind is:
* Why would I declare a charset in either specification or implementation and not in the other.
That leads me to another question:
* In case I have different values such as, in your case, `application/json` and `application/json;charset=utf-8`, wouldn't I wanna know that there is a difference?

**Comment by terribleherbst** [comment]
For the first question:
In my case the api specification is not from me but some kind of "given" from an external contract. Spring Boot returns by default `application/json;charset=UTF-8`. I consider it a good think to include the charset. This is not ideal, and maybe I should drop the charset cause it is not part of the OpenAPI spec. The most flexible way would be if I could configure, how strict the check should be.

For the second:
I would like to have some information as warning but also the test passing.

**Comment by cc-jhr** [comment]
For hikaku I want to keep the configuration parameters as low as possible.

About parameters of media types in general:
> The presence or absence of a parameter might be significant to the processing of a media-type, depending on its definition within the media type registry.

_Source:_ https://tools.ietf.org/html/rfc7231#section-3.1.1.1

And specifically on the charset parameter of media types:

>The default charset of ISO-8859-1 for text media types has been removed; the default is now whatever the media type definition says.

So basically, from my understanding, each media type definition registered at the iana has to define whether a parameter is significant or not and the possibility and value of a default parameter.

_Source:_ https://tools.ietf.org/html/rfc7231#appendix-B

Interestingly enough is that the charset parameter hasn't been officially defined for _application/json_: 
> Note:  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

_Source:_ https://tools.ietf.org/html/rfc8259

From my perspective it is too much effort to check each media type definition for it's parameters individually.
So in case there is a divergence it might or might not be significant. Currently I don't like the idea of adding some fuzzy state which would indicate that the test is successful, but it contains warnings.
Fact is that there is a difference and as a user of hikaku I would adjust either the implementation or the specification.
In your specific case I would just change the produces in the spring application to _application/json_.

I absolutely agree with you that in terms of *processing a request* `application/json;charset=UTF-8` could be seen as equal to `application/json`. From the perspective of equality, seeing specification and implementation as some kind of document, I would say, that they are not equal. And I would expect this behavior from hikaku.

**Comment by terribleherbst** [comment]
I am personal a big fan of restrictive checking my own work but want software to be as flexible as possible regarding someone else work. I am not deep in the reporter stuff, but I guess there is still some room for improvement to show **what** is different in specification and implementation.

To keep hikaku simple I guess you should keep it as it is and close the issue for now.

**Comment by cc-jhr** [comment]
> I am not deep in the reporter stuff, but I guess there is still some room for improvement to show what is different in specification and implementation.
I am sure there is ;)
