### ISSUE TITLE
Wrong file encoding leads to unclear error message

### ISSUE THREAD

**Issue by lmller** [codecentric/hikaku#27]
**Setup information**
hikaku version: 1.1.1 (probably also in 2.0.0)
specification converter: OpenApi
OS: Windows 7 Enterprise

**Describe the bug**
If the open api specification file (e.g. `openapi.json`) is is read with other encoding than UTF-8 (happens on windows, apparently), then the following line in the OpenApiConverter results in an error, because `openApi` will be `null`:
```
 val openApi = OpenAPIV3Parser().readContents(specificationContent, null, null).openAPI
```
Though the encoding error is expected, it is shadowed by an `IllegalStateException` thrown by the illegal null access. The encoding error is not an exception, but a message inside the `SwaggerParseResult`

**Expected behavior**
The encoding  error should be presented to the user.

**Comment by cc-jhr** [comment]
Please check version 2.0.0. In such a case an EndpointConverterException should be throws as stated in  https://github.com/codecentric/hikaku/releases/tag/v2.0.0

**Comment by lmller** [comment]
So do you think the issue is already fixed (I don't think so) or do you want me to throw a different exception and this is actually a remark on my PR? 😅

**Comment by cc-jhr** [comment]
Missed the part, that the acutal cause lies within the SwaggerParseResult, sorry.
