### ISSUE TITLE
Evaluate possibility to check response objects

### ISSUE THREAD

**Issue by cc-jhr** [codecentric/hikaku#30]
It would be beneficial to check the structural equality of data transfer objects (DTO) as well.
* Check possibilites to retrieve that data throughout existing converters
* Brainstorm hikaku internal presentation or data structure
* Think about ways to present results in CommandLineReporter

**Comment by terribleherbst** [comment]
Cause the description is empty, guess this is more or less a marker? What do you mean with DTO in this context?

**Comment by cc-jhr** [comment]
Good point. Totally forgot to add a description. DTO as in Data Transfer Object. The object that gets serialized into json for example. Eiter for request or as response object. It would be a real benefit to be able to check those as well.

**Comment by terribleherbst** [comment]
Thansk for the information. Do you know if there is any chance to extract this information at runtime from the SpringConverter?

**Comment by cc-jhr** [comment]
Part of this issue is to clarify this question ;)
Haven't had a look at it, but I guess it should be possible. Of course there are special cases such as using _org.springframework.http.ResponseEntity_ object.

**Comment by cc-jhr** [comment]
I would like to share my thoughts about this. Starting with response objects (not request payload objects) I thought about the following:
I think the first approach should be **easy** _and_ **lightweight**.

## internal representation
So for the internal representation I would use `org.json`. It supports a good API for creating nested object structures supporting objects and arrays. I also think it's sufficient to only differentiate between _object_, _string_ and _number_ as type. Equality check on `JSONObject` however also checks instances.

```
val a = JSONObject()
a.put("field1", 0)

val b = JSONObject()
b.put("field1", 0)

assertThat(a).isEqualTo(b)
```

```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"{"field1":0} (JSONObject@7db5b890)">
to be equal to:
 <"{"field1":0} (JSONObject@407b8435)">
but was not.
Expected :{"field1":0}
Actual   :{"field1":0}
```
Either need to check whether this can be handled or use a different object type. Of course it's possible to build a minimal data structure.

## specifications
I don't see a propblem here for RAML or OpenAPI. For both we can traverse the objects provided by the respective parser and create a JSONObject. Haven't checked WADL yet.

## implementations
Here it gets really interesting. Aside from any edge cases like using `ResponseEntity` object in spring for example this one is tricky. So we can get a `Class<*>`. This is a good first step.

Afaik we cannot use this directly with Gson or Jackson. We would need to create an instance of it and then pass it. Creating an instance is out of the question, because we cannot provide the constructor's parameters, that may exist and I don't want to make a convention like "a no-argument constructor has to be provided".

So instead it would be possible to traverse the fields using reflection. Problem is that fields might be annotated changing names for the serialized output or excluding fields from being serialized. And of course there is a great variety of libraries proving such annotations.

This is what I got so far. So I didn't even bother thinking about the representation in the `CommandLineReporter`. I'm open for ideas.

**Comment by cc-jhr** [comment]
We decided that we won't support http status codes, request objects and response objects on Endpoints. On the implementation side this is way too dynamic to actually handle this with static code analysis.
