### ISSUE TITLE
Add list of responses for OpenApiConverter

### ISSUE THREAD

**Issue by BranislavLazic** [codecentric/hikaku#35]
Affects: OpenApiConverter

I would like to assert whether an endpoint contains one of responses as stated in a contract (at least status codes).

Proposed solution: 
Endpoint class would contain additional property: responses/response. Add additional "extractor" to perform extraction of responses/response.

**Comment by cc-jhr** [comment]
Hi @BranislavLazic,

thank you for your request.

Response objects are already a topic in #30. However this only relates to the data transfer objects, not  the status codes. From your description I understand that the status codes are more relevant to you than the response objects. Is that correct? In that case I would only focus on status codes within this issue.

Since you requested this solely for the OpenApiConverter I wanted to know whether you are using a hikaku implementation converter (either for spring-mvc or jax-rs) or if you implemented the `EndpointConverter` interface yourself. This feature would be so general that in best case all converters would have to support it in order to be useful. However especially for the implementation converters I currently have no idea how to implement that. Response objects are tricky, but status codes really got me thinking whether or not this is possible.

**Comment by BranislavLazic** [comment]
Hi @cc-jhr 
It's intended to be used with Spring. But also, in general manner too ("bare bones" `Endpoint` instances asserted against specification). But I thought it would be best to start from OpenApiConverter itself. Yes, status codes are more relevant (response objects would be also nice). Also, I understand what you're speaking about. Response status codes can be extracted fairly easy and packed into `Endpoint` instance. However, assertion against implementation is not so easy.

Example:

Let's say we have this specification:

```
openapi: 3.0.2
info:
  version: 1.0.0
  title: Todo List
paths:
  /todos:
    get:
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '422':
          description: Unprocessable entity
components:
  schemas:
    Todo:
      type: array
      items:
        type: string
```

And this is the test (note `response` property in `Endpoint`):

```
    @Test
    fun `multiple status codes`() {
        //given
        val file = Paths.get(this::class.java.classLoader.getResource("responses/responses_multiple.yaml").toURI())
        val implementation = setOf(
                Endpoint(
                        path = "/todos",
                        httpMethod = HttpMethod.GET,
                        produces = setOf("application/json"),
                        responses = setOf("200")
                )
        )

        //when
        val specification = OpenApiConverter(file)

        //then
        Assertions.assertThat(specification.conversionResult).containsExactlyInAnyOrderElementsOf(implementation)
    }
```

Test fails since status codes in implementation do not match status codes in specification. Although, implementation is legit because it contains **one of** status codes enlisted in specification and that's totally fine.
Things are even harder from aspect of Spring. If we observe implementation from Spring configuration, it would look something like this:

```
@RequestMapping(value = "/todos", produces = APPLICATION_JSON_VALUE)
fun getAllTodos() = ResponseEntity.status(200).body( ... )
```
I'm not sure how to determine (possible) status codes produced by that method. Or should they be even asserted in case of Spring config?

Overall, if you want to go with this feature, please consider this assertion of specification against implementation.

**Comment by cc-jhr** [comment]
I'd rather only add a new "feature" (speaking in terms of `SupportedFeatures.kt`) if I know that I can have it in both specification as well as implementation.

I don't see a benefit in only implementing it in OpenApiConverter to use it in a test case like you posted it:
```
@Test
    fun `multiple status codes`() {
        //given
        val file = Paths.get(this::class.java.classLoader.getResource("responses/responses_multiple.yaml").toURI())
        val implementation = setOf(
                Endpoint(
                        path = "/todos",
                        httpMethod = HttpMethod.GET,
                        produces = setOf("application/json"),
                        responses = setOf("200")
                )
        )

        //when
        val specification = OpenApiConverter(file)

        //then
        Assertions.assertThat(specification.conversionResult).containsExactlyInAnyOrderElementsOf(implementation)
    }
```

In this case it would make a lot more sense to me to use the swagger-parser directly.

As for the spring implementation you pretty much summed up the problems that I see. 

Using `ResponseEntity` object is one way and nothing stops me from having wicked logic that leads to the actual value in the method.
There is also `ResponseStatus` annotation on exception classes, but I would have to know that the entry point of the REST controller can actually throw this. Another possibility is `ControllerAdvice` with `ExceptionHandler`.
For JAX-RS it's a different class (`javax.ws.rs.core.Response`), but the same deal.

**Comment by cc-jhr** [comment]
Response objects are to be discussed in #30.

As for the response codes: Since I see response codes more as part of the REST APIs behaviour and not as something that you can easily analyze with static code analysis I will close this issue.
