### ISSUE TITLE
Tests for JaxRsConverter and MicronautConverter fail on windows machine

### ISSUE THREAD

**Issue by cc-jhr** [codecentric/hikaku#38]
I've cloned the project on a windows machine using gitbash and executed the tests via command line.
The tests for micronaut and jax-rs are failing.
This probably relates to the code that searches for classes within the project. (That's why I labeled core as well).

I have not checked whether or not this would be the same result for a hikaku based tests using one of the mentioned converters.

**Comment by cc-jhr** [comment]
Tried to add windows as os to the travis-ci build, but it is not supported:

> The language 'java' is currently unsupported on the Windows Build Environment.
>
> Let us know if you'd like to see it: https://travis-ci.community/c/environments/windows. Thanks for understanding!

**Comment by uuf6429** [comment]
> Tried to add windows as os to the travis-ci build, but it is not supported:

Maybe consider additionally [using appveyor](https://www.appveyor.com/docs/windows-images-software/#java)? (it's free for open source, like travis)
Or use [the custom approach](https://travis-ci.community/t/java-support-on-windows/286/5) in Travis?

**Comment by cc-jhr** [comment]
Thanks. I added a new issue for that. Referencing your comment.
