### ISSUE TITLE
Unable to get code running on OpenJDK 11

### ISSUE THREAD

**Issue by terribleherbst** [codecentric/hikaku#49]
# Setup information
**hikaku version: 3.0.0**
**specification converter: OpenApiConverter** 
**implementation converter: SpringConverter** 
**build tool and version:** `gradle-5.6.2`
**test framework:** `SpockFramework`

# Describe the bug
Hikaku is unable to run test using Java 11
```
hikaku.match()
|      |
|      de.codecentric.hikaku.converters.EndpointConverterException: Retrieving groups by name is not supported on this platform.
|      	at de.codecentric.hikaku.converters.openapi.OpenApiConverter.convert(OpenApiConverter.kt:46)
|      	at de.codecentric.hikaku.converters.AbstractEndpointConverter$conversionResult$2.invoke(AbstractEndpointConverter.kt:11)
|      	at de.codecentric.hikaku.converters.AbstractEndpointConverter$conversionResult$2.invoke(AbstractEndpointConverter.kt:8)
|      	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
|      	at de.codecentric.hikaku.Hikaku.match(Hikaku.kt:41)
|      	at com.kws.cultivent.fieldservice.FieldManagementApiIntegrationTest.Check IMPLEMENTATION and SPECIFICATION(FieldManagementApiIntegrationTest.groovy:67)
|      Caused by: java.lang.UnsupportedOperationException: Retrieving groups by name is not supported on this platform.
|      	at kotlin.internal.jdk8.JDK8PlatformImplementations.getMatchResultNamedGroup(JDK8PlatformImplementations.kt:28)
|      	at kotlin.text.MatcherMatchResult$groups$1.get(Regex.kt:259)
|      	at kotlin.text.jdk8.RegexExtensionsJDK8Kt.get(RegexExtensions.kt:33)
|      	at de.codecentric.hikaku.converters.openapi.extractors.QueryParameterExtractor.extractQueryParametersFromComponents(QueryParameterExtractor.kt:30)
|      	at de.codecentric.hikaku.converters.openapi.extractors.QueryParameterExtractor.invoke(QueryParameterExtractor.kt:12)
|      	at de.codecentric.hikaku.converters.openapi.OpenApiConverter.parseOpenApi(OpenApiConverter.kt:70)
|      	at de.codecentric.hikaku.converters.openapi.OpenApiConverter.convert(OpenApiConverter.kt:44)
|      	... 5 more
```

# Expected behavior
Code should work in the same way as on JDK 8 or any idea for a workaround

# Code samples
Can you provide specification snippets or code snippets?
```
new Hikaku(
        openApiConverter,
        springConverter,
        hikakuConfig
      ).match()
```

**Comment by terribleherbst** [comment]
This might be related to this kotlin problem https://youtrack.jetbrains.com/issue/KT-29241

**Comment by terribleherbst** [comment]
Any news on this?

**Comment by cc-jhr** [comment]
We had this issue reported before, but the original author didn't reply so I closed the issue: #33 
The code snippet you provided is not helpful. I know how to instantiate the Hikaku class. It would be beneficial if you could provide a **minimal example** of an OpenAPI specification with which you can reproduce the problem.

**Comment by terribleherbst** [comment]
Sorry I did bot see the closed issue. Thanks for your help.
 I will create a minimal example project for reproduction.

**Comment by terribleherbst** [comment]
Will check again using version 3.0.1

**Comment by cc-jhr** [comment]
Any update on this? Otherwise I'd close this issue.

**Comment by terribleherbst** [comment]
Oh sorry for that. Yes after updgrading to the next version everythink is fine. Thanks for the help and sorry about the missing information. So please close the issue.

**Comment by cc-jhr** [comment]
No problem. I'm glad it's working for you now.
