### ISSUE TITLE
ResponseEntity<Unit> produces 'application/json'

### ISSUE THREAD

**Issue by clamothe** [codecentric/hikaku#52]
# Setup information
**hikaku version: 3.1.2**
**specification converter: OpenAPI** 
**implementation converter: Spring MVC** 

# Describe the bug
Methods that return `ResponseEntity<Unit>` are assumed to produce `'application/json'` content.

# Expected behavior
`ResponseEntity<Unit>` should be interpreted in the same way as if the method had no return type. It should not be considered to produce content of any type.

# Code samples
Kotlin
```
@RestController
@Validated
@RequestMapping("")
class Controller {


    @RequestMapping(
        value = ["/api/rest/v1/{id}"],
        consumes = ["application/json"],
        method = [RequestMethod.PUT])
    fun updateIssuerOrganization( @PathVariable("id") id: kotlin.String
, @Valid @RequestBody body: kotlin.String?
): ResponseEntity<Unit> {
        return ResponseEntity.ok().build()
    }
}
```

**Comment by lmller** [comment]
Hey @clamothe!
Imho, this is working as expected.
Returning `Unit` (aka. "no return value") is not the same as returning an `ResponseEntity<Unit>`, it's behaving the same way as returning a `ResponseEntity<Void>`.

Also, Hikaku can't know which behavior a user expects.

**Comment by cc-jhr** [comment]
Apart from what @lmller wrote, I don't see a possibility to retrieve the type of the generic.
