### ISSUE TITLE
Allow undeclared endpoints

### ISSUE THREAD

**Issue by clamothe** [codecentric/hikaku#54]
**Is your feature request related to one or multiple existing converters?**
OpenAPI

**Describe the solution you'd like**
Allow tests to pass so long as the endpoints declared in your application contain all of the endpoints declared in the specification.

This differs from the current apparent behavior in that endpoints declared by your application but not in your spec will be allowed. This could be enabled with a flag.

**Comment by cc-jhr** [comment]
Hi @clamothe ,

the idea of hikaku is that the equality is given if specification and implementation offer the exact same endpoints. However, if for some reason you do not want to consider certain endpoints for matching, you can add a filter to the 'HikakuConfig'.
